@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

AddElementTag("fallback", $bgColor="#444444")


Person(user_customer, "Покупатель")
Person(user_accountant, "Бухгалтер")
Person(user_programmer, "Продуктолог")

System(system_shop, "SaaS магазин", "Позволяет покупателю покупать товары и изменять тарифы")

System_Ext(system_email, "Почтовый сервис", "n8n - отправка сообщений клиенту через n8n на электронную почту")
System_Ext(system_bank, "Платежный шлюз", "Sber - страница оплаты продукта")
System_Ext(system_docs, "Сервис ЭДО", "Диадок - сервис подписания электронных документов")
System_Ext(system_ops, "OPS сервис", "Сервис приложений магазина")

Rel(user_customer, system_shop, "Просмотр продуктов, покупка продуктов, изменение тарифа")
Rel(user_accountant, system_shop, "Ручное изменение статуса оплаты")
Rel(user_programmer, system_shop, "Настраивает продукты")
Rel(system_shop, system_email, "Отправка сообщений покупателю")
Rel_R(system_shop, system_bank, "Перенаправление пользователя на страницу оплаты продукта")
Rel_R(system_bank, system_shop, "Отправка статуса оплаты")
Rel(system_shop, system_docs, "Перенаправление пользователя для подписания документов")
Rel(system_shop, system_ops, "Запуск/остановка приложения; изменение кол-ва лицензий")

@enduml