@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user_customer, "Покупатель")
Person(user_accountant, "Бухгалтер")
Person(user_programmer, "Продуктолог")

System(system_shop, "SaaS магазин", "Позволяет покупателю покупать товары и изменять тарифы")

System_Ext(system_email, "Почтовый сервис", "n8n - отправка писем клиенту через n8n на электронную почту")
System_Ext(system_bank, "Платежный шлюз", "Sber - страница оплаты продукта")
System_Ext(system_docs, "Сервис ЭДО", "Диадок - сервис подписания электронных документов")
System_Ext(system_ops, "OPS сервис", "Сервис приложений магазина")
System_Ext(system_site, "Сайт визитка", "Сайт с продуктами и их тарифами")

System_Boundary(system_shop, "SaaS магазин") {
    ContainerQueue(system_queue, "Брокер сообщений", "RabbitMQ")
    Container(system_flow, "Сервис автоматизация", "n8n")

    Container(system_admin, "Сервис продуктов", "Strapi CMS")
    Container(system_sign, "Сервис клиентов", "Keycloak")
    Container(system_billing, "Сервис заказов", "NodeJs")
    
    Container(system_account_front, "Личный кабинет\n клиента", "VueJs + Vuetify")
    Container(container_widget, "Виджет", "VanillaJs")
    Container(container_accountant_admin, "Личный кабинет бухгалтера", "Angular")
    
    ContainerDb(container_db, "База данных", "PostgreSql")
}

Rel(system_site, container_widget, "Встраивание виджета тарифов")
Rel(container_widget, system_admin, "Чтение тарифов")

Rel(user_accountant, container_accountant_admin, "Ручное изменение статуса оплаты; Просмотр счетов, документов, пользователей")
Rel(container_accountant_admin, system_billing, "Ручное изменение статуса оплаты; Просмотр счетов, документов, пользователей")

Rel(user_programmer, system_admin, "Создание/ Изменение/ Удаление продуктов")

Rel(system_admin, container_db, "Создание/ Изменение/ Удаление продуктов")
Rel(system_sign, container_db, "Регистрация/ Получение пользователей")
Rel(system_billing, container_db, "Создание заказов; Изменение статуса оплаты; Чтение заказов")

Rel(system_account_front, system_admin, "Чтение продуктов")
Rel(system_account_front, system_billing, "Создание заказа; Изменение кол-ва лицензий; Запрос акта; Просмотр купленных продуктов")
Rel(user_customer, system_account_front, "Создание заказа; Изменение кол-ва лицензий; Запрос акта; Просмотр купленных продуктов")
Rel(user_customer, system_site, "Просмотр продуктов")
Rel(system_account_front, system_sign, "Аутентификация; Регистрация; Восстановление пароля")

Rel(user_customer, system_bank, "Оплата продукта")
Rel(user_customer, system_docs, "Подписание документов")
Rel_L(system_billing, system_bank, "Создание формы оплаты")
Rel(system_bank, system_flow, "Отправка статуса оплаты")

Rel(system_flow, system_email, "Отправка писем покупателю")

Rel(system_billing, system_docs, "Создание акта")

Rel_U(system_flow, system_queue, "Чтение/ Создание событий")
Rel(system_admin, system_queue, "Продукт Созданан/ Изменен/ Удален")
Rel(system_sign, system_queue, "Пользователь зарегистрирован")
Rel(system_billing, system_queue, "Запуск/остановка приложения; Изменение кол-ва лицензий")
Rel(system_ops, system_queue, "Статус OPS операции")
Rel(system_ops, system_queue, "Чтение событий: Запуск/остановка приложения; Изменение кол-ва лицензий")

Rel(system_docs, system_flow, "Документы подписаны")

@enduml