@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user_customer, "Покупатель")

ContainerQueue(system_queue, "Брокер сообщений", "RabbitMQ")

Container(system_account_front, "Личный кабинет покупателя", "VueJs + Vuetify")

ContainerDb(container_db, "База данных", "PostgreSql")

Container_Boundary(system_admin1, "Сервис аутентификации") {
    Component(system_sign, "Сервис аутентификации", "Keycloak")
}

Rel(system_sign, container_db, "Регистрация/ Получение пользователей")
Rel(user_customer, system_account_front, "Аутентификация; Регистрация; Восстановление пароля")
Rel(system_account_front, system_sign, "Аутентификация; Регистрация; Восстановление пароля")
Rel(system_sign, system_queue, "Пользователь зарегистрирован, залогинился, восстановление пароля")

@enduml