@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Ext(system_email, "Почтовый сервис", "n8n - отправка писем клиенту через n8n на электронную почту")
System_Ext(system_bank, "Платежный шлюз", "Sber - страница оплаты продукта")
System_Ext(system_docs, "Сервис ЭДО", "Диадок - сервис подписания электронных документов")

ContainerQueue(system_queue, "Брокер сообщений", "RabbitMQ")
Container(system_flow, "Автоматизация", "n8n")

Container(system_admin, "Сервис продуктов", "Strapi CMS")

Container(system_account_front, "Личный кабинет покупателя", "VueJs + Vuetify")
Container(container_accountant_admin, "Личный кабинет бухгалтера", "Angular")

ContainerDb(container_db, "База данных", "PostgreSql")

Container_Boundary(system_admin1, "Сервис заказов") {
    Component(system_billing, "API заказов", "C# Class")
    Component(component_billing, "Компонент заказов", "C# Class")
    Component(component_docs, "Компонент ЭДО", "C# Class")
    Component(component_ops, "Компонент OPS", "C# Class")
    Component(component_crud, "CRUD Generated API For Admin", "C# Class")
    Component(component_cron, "Выполнение регулярных задач")
}

Rel(container_accountant_admin, component_crud, "Ручное изменение статуса оплаты; Просмотр счетов, документов, пользователей")
Rel(component_crud, container_db, "Ручное изменение статуса оплаты; Просмотр/создание счетов, документов, пользователей")
Rel(system_billing, component_billing, "Создание заказов; Изменение статуса оплаты")
Rel(component_billing, system_admin, "Чтение продуктов")
Rel(system_billing, container_db, "Чтение заказов")
Rel(system_account_front, system_billing, "Создание заказа; Изменение кол-ва лицензий; Запрос акта; Просмотр купленных продуктов")
Rel(component_cron, component_billing, "Запуск автосписания средств")
Rel(component_cron, system_queue, "Письмо о предстоящем списании")

Rel(system_account_front, system_bank, "Переход на страницу оплаты продукта")
Rel(component_billing,  system_bank, "Создание формы оплаты")
Rel(component_billing,  system_queue, "Чтение статуса оплаты")
Rel(component_billing,  component_ops, "Запрос на запуск/ остановку/ обновление приложения")
Rel(component_billing,  component_docs, "Запрос на создание счета-оферты")
Rel(system_billing,  component_docs, "Запрос на создание акта")
Rel(system_bank, system_flow, "Отправка статуса оплаты")

Rel(system_flow, system_email, "Отправка писем покупателю")

Rel(system_account_front, system_docs, "Переход на подписание документов")
Rel(component_docs, system_docs, "Создание документа")

Rel(component_docs, system_queue, "Чтение статуса подписания документов")
Rel_U(system_flow, system_queue, "Чтение/ Создание событий")
Rel(component_ops, system_queue, "Чтение статуса OPS операции")
Rel(component_ops, system_queue, "Чтение событий: Запуск/остановка приложения; Изменение кол-ва лицензий")

Rel(system_docs, system_flow, "Документы подписаны")

@enduml